### ISSUE TITLE
Вылет при удалении первого изображения в создании заметки

### ISSUE THREAD

**Issue by Alex009** [Alex009/traineeship-ak-ak-android#16]
Шаги:
1. Зашел в создание задачи;
2. Ввел текста;
3. Добавил 3 изображения;
4. Нажал на кнопку удалить у первого изображения;

ОР: первое изображение удалено;
ФР: вылет.

**Comment by kharitonov1995** [comment]
Вылетало приложение из-за того, что когда CreateNoteActivity используется для создания заметки поле mEditNote = null, а при удалении происходит обращение к нему для установки флага, по которому происходит проверка при удалении, когда заметка редактируется.
