### ISSUE TITLE
Оформить экран создания заметки в соответствии с дизайном

### ISSUE THREAD

**Issue by kharitonov1995** [Alex009/traineeship-ak-ak-android#3]
1. При добавлении должен быть заголовок "Новая заметка"

2. Текст должен быть не подчеркнутый

3. Добавить разделительную черту между заголовком заметки и текстом заметки

4. Добавить меню внутри странички. Создать пункты меню:
 -Прикрепить изображение (При выборе этого пункта показывается выбор приложений Камера или Галерея)
 -Закрыть без сохранения (При выборе этого пункта стирается вся информация и показывается главный экран)

5. При нажатии на кнопку назад сохранять заметку

![notes2](https://cloud.githubusercontent.com/assets/18188165/15105858/f3b3d1f2-15e6-11e6-9576-8e632a46521f.png)
![notes3](https://cloud.githubusercontent.com/assets/18188165/15105859/f3b85628-15e6-11e6-995f-b03d5b096a92.png)
![123](https://cloud.githubusercontent.com/assets/18188165/15106167/43546396-15e9-11e6-9ec8-c383fd615392.jpg)

**Comment by Alex009** [comment]
* Задачи должны иметь осмысленное название (пример: "Реализовать возможность прикреплять множество изображений к заметке", "Оформить экран создания заметки в соответствии с дизайном");
* В описании задачи нужно изложить все что требуется сделать и все материалы которые понадобятся (макеты, дизайн, иконки, ссылки);
* Так же при начале работы над задачей в комментарий нужно описать декомпозицию задачи (по пунктам что требуется сделать для реализации) и предполагаемое время на каждый пункт (чтобы сами вы могли потом проанализировать свои оценки и фактические затраты времени - важно уметь ставить как можно более точные оценки).

Пример задачи: #1

**Comment by kharitonov1995** [comment]
1. Установить заголовок "Новая заметка" в Toolbar (5 мин)
2. В EditText убрать подчеркивание текста (5 мин)
3. Создать в лейауте создания заметки View с высотой 1dp и шириной match_parent (5 мин)
4. Создать меню из двух элементов. При нажатии на пункт "Прикрепить изображение" показывать диалог с выбором приложения. (30 мин)
5. Очистить все View и вернуться на главный экран (5 мин)
