### ISSUE TITLE
Реализовать возможность хранения множества изображений

### ISSUE THREAD

**Issue by axel9kislin** [Alex009/traineeship-ak-ak-android#4]
1)Внести изменения в DataBaseHelper, в таблицу notes. Убрать поле таблицы, используемое для хранения единственного пути к изображению. (5m)
2)Добавить таблицу imagepaths, в которой по id заметки из первой таблицы сохраняется путь изображения. Соединить таблицу внешний ключом с таблицей notes, реализовать каскадное обновление и удаление данных. (30m).
3)Отредактировать модель заметки для поддержки множества изображений. (20m)
4)Реализовать и протестировать запись и чтение заметки в базу данных. (15m)
5)Переписать функции доступа к базе данных в соответствие с новой структурой, протестировать работоспособность в местах вызова. (2h)

**Comment by Alex009** [comment]
* Задачи должны иметь осмысленное название (пример: "Реализовать возможность прикреплять множество изображений к заметке", "Оформить экран создания заметки в соответствии с дизайном");
* В описании задачи нужно изложить все что требуется сделать и все материалы которые понадобятся (макеты, дизайн, иконки, ссылки);
* Так же при начале работы над задачей в комментарий нужно описать декомпозицию задачи (по пунктам что требуется сделать для реализации) и предполагаемое время на каждый пункт (чтобы сами вы могли потом проанализировать свои оценки и фактические затраты времени - важно уметь ставить как можно более точные оценки).

Пример задачи: #1 

Отредактируй задачу, пожалуйста.

**Comment by axel9kislin** [comment]
Задача выполнена, не закрываю до код ревью.

**Comment by Alex009** [comment]
создай Pull request со своей ветки в master. Но не нажимай accept merge.

**Comment by Alex009** [comment]
ветка влита.
